trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: PI_AFGSG_DotNet
  - name: run_import
    value: false
  - name: run_delete
    value: false

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'AFServerName, AFDatabaseName'

      - script: |
          for /D %%a in (".\*.*") do xcopy /y /d appsettings.json "%%a\"
        displayName: 'copy file to subfolders'

      - script: |
          "%pihome64%\af\afimport" "\\OCSSAMPLESAPI01\Green Power Company" /F:"AF Database - Green Power Company.xml" /P
        condition: eq(variables.run_import, true)
        displayName: 'import database2'

      - script: |
          nuget restore
        displayName: 'Nuget restore'

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          arguments: --filter Category=Solution
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'

      - task: DotNetCoreCLI@2
        displayName: 'Run Delete'
        condition: eq(variables.run_delete, true)
        inputs:
          command: test
          arguments: --filter Category=Delete
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS) (Delete)'

  - job: Analysis
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - script: |
          nuget restore
        displayName: 'Nuget restore'

      - template: '/miscellaneous/build_templates/binskim.yml@templates'

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
        parameters:
          language: dotnet
