trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: OpsGuildPipelineTools
      type: git
      name: Engineering/opsguild.pipeline-tools
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: PI_AFGSG_DotNet
  - name: run_import
    value: false
  - name: run_delete
    value: false

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - checkout: self
      - checkout: OpsGuildPipelineTools
      
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'AFServerName, AFDatabaseName'
          
      - template: '/Templates/Utilities/InstallAFSDK.step.v0.yml@OpsGuildPipelineTools'

      - script: |
          for /D %%a in (".\*.*") do xcopy /y /d appsettings.json "%%a\"
        displayName: 'copy file to subfolders'
        workingDirectory: $(Build.SourcesDirectory)\AF-SDK-Getting-Started-Guide

      - script: |
          "%pihome64%\af\afimport" "\\OCSSAMPLESAPI01\Green Power Company" /F:"AF Database - Green Power Company.xml" /P
        condition: eq(variables.run_import, true)
        displayName: 'import database2'
        workingDirectory: $(Build.SourcesDirectory)\AF-SDK-Getting-Started-Guide

      - script: |
          nuget restore
        displayName: 'Nuget restore'
        workingDirectory: $(Build.SourcesDirectory)\AF-SDK-Getting-Started-Guide

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          arguments: --filter Category=Solution
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
          projects: '$(Build.SourcesDirectory)\AF-SDK-Getting-Started-Guide\Getting-Started-With-PI-AF-SDK.sln'

      - task: DotNetCoreCLI@2
        displayName: 'Run Delete'
        condition: eq(variables.run_delete, true)
        inputs:
          command: test
          arguments: --filter Category=Delete
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS) (Delete)'

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - script: |
            nuget restore
          displayName: 'Nuget restore'

        - template: '/miscellaneous/build_templates/binskim.yml@templates'

        - template: '/miscellaneous/build_templates/analysis.yml@templates'
          parameters:
            language: dotnet
